### ISSUE TITLE
HunSpell Release v1.7.2 Doesn't Actually Run

### ISSUE THREAD

**Issue by othmanalikhan** [iquiw/hunspell-binary#1]
**Environment**
- Windows 11 Pro (22621.2134)

**Problem**

It seems that the pre-compiled binaries for release v1.7.2 don't run properly. After download, extracting the ZIP, and running the command `hunspell.exe -D`, the binary 'runs' but no output is seen.

**Fixes Attempted**

- I've tried downloading releases v1.7.0 and v1.7.1 and both display output as expected.

**Comment by iquiw** [comment]
I see. I think I noticed the problem before, but forgot it as I do not use hunspell daily basis (aspell instead ;).

I will check it, but have no clue for now.

**Comment by othmanalikhan** [comment]
No worries, I thought I would open an issue in case others come across the same issue. For the time being, using an earlier release v1.7.1 is not a bad workaround considering it is only a minor revision behind.

**Comment by iquiw** [comment]
@othmanalikhan  Can you try this one?

https://github.com/iquiw/hunspell-binary/releases/tag/v1.7.2

| File | SHA-256 sum |
| ---  | ---         |
| hunspell-v1.7.2.7z | `9234ab41e0fab218839435e2ca0ecf040ce2becddb054511932e38f3640972f2` |

**Comment by othmanalikhan** [comment]
Just tested it out and can confirm it works perfectly as standalone executable but also works perfect with my Emacs setup like the previous versions.

Thanks for the fix! Out of interest, how did you resolve the issue?

**Comment by clach04** [comment]
👍 Confirmed works for me too :-)

**Comment by iquiw** [comment]
Thank you for the confirmation.

> Thanks for the fix! Out of interest, how did you resolve the issue?

I included the necessary DLL files that hunspell.exe depends on.

**Comment by othmanalikhan** [comment]
So today I was doing a bit of Arabic translation work and unfortunately discovered the new release 1.7.2 of Hunspell though seems to work on the surface doesn't actually work properly.

Using the same Arabic dictionary file `ar.aff` and `ar.dic` that work with no issues on version 1.7.1, running the following command on CLI, to check whether the word 'سلام' is a valid word (which it is), yields that it is an invalid word:

```
$ echo "السلام" | hunspell -d ar
Hunspell 1.7.2
# السلام 0
```
 
The 0 in the result implies the word is not found but it should have been. 

I've rolled back to Hunspell v1.7.1 for now and probably will just wait for Hunspell v1.7.3 to be released on the original upstream repo until it goes pushed into this CI/CD integration pipeline.
